[package]
name = "posbc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.65"
chrono = "0.4.22"
ed25519 = "1.5.2"
openssl = "0.10.42"
p256 = { version = "0.11.1", features = ["ecdsa-core"] }
rand = { version = "0.8.5", features = ["std_rng"] }
secp256k1 = { version = "0.24.0", features = ["rand"] }
serde = "1.0.145"
serde_json = "1.0.86"
signature = "1.6.4"
