@startuml
!include blocks.puml
allowmixing

' `-`: private, `#`: protected, `~`: package private, `+`: public
class "Account" as acct {
  -id: ""AccountId - secp256k1::PublicKey""
  -balance: ""u128""
}

@enduml