@startuml
allowmixing

' `-`: private, `#`: protected, `~`: package private, `+`: public
class "Block" as bl {
  +transactions: ""BTreeMap<TxnId, Txn>""
  +prev_blockhash: TxnHash
  +leader: PbKey
  +block_ct: u128
}

actor klaus

klaus -> bl::transactions

@enduml