# .github/workflows/release-please.yml
name: release-please
on:
  push:
    branches:
      - main
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: mrlucciola/release-please-action@main
        with:
          release-type: rust # Multiple release types are supported
          default-branch: main
